# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.0.9
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: ETC
has_binder: true
has_settings: true
kind: server
labextension_name: '@educational-technology-collective/etc_jupyterlab_notebook_state_provider'
project_short_description: A JupyterLab extension.
python_name: etc_jupyterlab_notebook_state_provider
repository: https://github.com/educational-technology-collective/etc_jupyterlab_notebook_state_provider.git
test: false

